name: Sync and Merge

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --local user.email "shuohao@126.com"
          git config --local user.name "shuohao"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/YueChan/Live.git
          git fetch upstream
          git pull --rebase upstream master
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          
      - name: Merge files
        run: |
          bash merge_files.sh

      - name: Commit and push changes
        run: |
          git add All.m3u
          git diff --exit-code || git commit -am "Merge files into All.m3u" 
          git push -f origin main
